name: Continuous integration

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Ensure files are formatted with black
      run: |
        pip install --upgrade pip
        pip install black~=23.3.0
        black --check --diff ./examples
  docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ensure the docker image works and can start.
      run: |
        make container-test
